baseURL = 'https://patricksheedy.com'
languageCode = 'en-us'
title = 'Patrick Sheedy - Software Developer'
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'github'
    tabWidth = 4

[params]
  author = "Patrick Sheedy"
  description = "Software Developer specializing in modern web technologies"
  email = "patricksheedy@gmail.com"
  github = "https://github.com/patricksheedy"
  linkedin = "https://linkedin.com/in/patricksheedy"
  twitter = "https://twitter.com/patrick_sheedy"
  googleAnalytics = "G-TP1L00RTZP"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts"
    weight = 1
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about"
#    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
